# Generated by Django 3.2.25 on 2025-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='blend',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
