# Generated by Django 3.2.25 on 2025-04-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_tea_blend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tea',
            table='products_tea',
        ),
    ]
