# Generated by Django 3.2.25 on 2025-04-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_tea_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tea',
            table='products_tea',
        ),
    ]
