# Generated by Django 3.2.25 on 2025-04-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250406_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.country'),
        ),
    ]
